// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Foundation

@usableFromInline struct CertificateList: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var tbsCertList: TBSCertList
    @usableFromInline var signatureAlgorithm: AlgorithmIdentifier
    @usableFromInline var signature: ASN1BitString
    @inlinable init(tbsCertList: TBSCertList, signatureAlgorithm: AlgorithmIdentifier, signature: ASN1BitString) {
        self.tbsCertList = tbsCertList
        self.signatureAlgorithm = signatureAlgorithm
        self.signature = signature
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let tbsCertList: TBSCertList = try TBSCertList(derEncoded: &nodes)
            let signatureAlgorithm: AlgorithmIdentifier = try AlgorithmIdentifier(derEncoded: &nodes)
            let signature: ASN1BitString = try ASN1BitString(derEncoded: &nodes)
            return CertificateList(tbsCertList: tbsCertList, signatureAlgorithm: signatureAlgorithm, signature: signature)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(tbsCertList)
            try coder.serialize(signatureAlgorithm)
            try coder.serialize(signature)
        }
    }
}
