// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct KEP_RevokedInfo: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var revocationTime: GeneralizedTime
    @usableFromInline var revocationReason: KEP_CRLReason?
    @inlinable init(revocationTime: GeneralizedTime, revocationReason: KEP_CRLReason?) {
        self.revocationTime = revocationTime
        self.revocationReason = revocationReason
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let revocationTime: GeneralizedTime = try GeneralizedTime(derEncoded: &nodes)
            let revocationReason: KEP_CRLReason? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in return try KEP_CRLReason(derEncoded: node) }
            return KEP_RevokedInfo(revocationTime: revocationTime, revocationReason: revocationReason)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(revocationTime)
            if let revocationReason = self.revocationReason { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serialize(revocationReason) } }
        }
    }
}
