// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct KEP_CrlIdentifier: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var crlissuer: DSTU_Name
    @usableFromInline var crlIssuedTime: UTCTime
    @usableFromInline var crlNumber: ArraySlice<UInt8>?
    @inlinable init(crlissuer: DSTU_Name, crlIssuedTime: UTCTime, crlNumber: ArraySlice<UInt8>?) {
        self.crlissuer = crlissuer
        self.crlIssuedTime = crlIssuedTime
        self.crlNumber = crlNumber
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let crlissuer: DSTU_Name = try DSTU_Name(derEncoded: &nodes)
            let crlIssuedTime: UTCTime = try UTCTime(derEncoded: &nodes)
            let crlNumber: ArraySlice<UInt8>? = try ArraySlice<UInt8>(derEncoded: &nodes)
            return KEP_CrlIdentifier(crlissuer: crlissuer, crlIssuedTime: crlIssuedTime, crlNumber: crlNumber)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(crlissuer)
            try coder.serialize(crlIssuedTime)
            if let crlNumber = self.crlNumber { try coder.serialize(crlNumber) }
        }
    }
}
