#!/bin/bash
set -eo pipefail

# Reuse the TS generation script for data if not present?
# Or we can just call openssl commands directly here.
# Let's rely on run_ts_openssl_tests.sh having run, OR generate our own.
# To be self-contained:

DATA_DIR="java_test_data"
mkdir -p "$DATA_DIR"

echo "Generating Test Data in $DATA_DIR..."

# 1. RSA Key
openssl genrsa -out "$DATA_DIR/key.pem" 2048
openssl pkcs8 -topk8 -in "$DATA_DIR/key.pem" -out "$DATA_DIR/pkcs8_key.pem" -nocrypt

# 2. CSR
openssl req -new -key "$DATA_DIR/key.pem" -out "$DATA_DIR/csr.pem" -subj "/C=US/ST=State/L=City/O=Org/CN=Test"

# 3. Self-signed Cert (CA)
openssl req -x509 -key "$DATA_DIR/key.pem" -out "$DATA_DIR/ca.crt" -subj "/C=US/ST=State/L=City/O=Org/CN=CA" -days 365

# 4. EE Cert
openssl x509 -req -in "$DATA_DIR/csr.pem" -CA "$DATA_DIR/ca.crt" -CAkey "$DATA_DIR/key.pem" \
    -out "$DATA_DIR/ee.crt" -days 30 -CAcreateserial

# 5. Extended Cert
cat > "$DATA_DIR/ext.cnf" << EOF
[req]
distinguished_name = req_dn
x509_extensions = v3_ext
[req_dn]
CN = Extended
[v3_ext]
basicConstraints = CA:FALSE
keyUsage = digitalSignature
subjectAltName = DNS:example.com
EOF
openssl req -x509 -key "$DATA_DIR/key.pem" -out "$DATA_DIR/extended.crt" -days 30 \
    -subj "/CN=Extended" -config "$DATA_DIR/ext.cnf"

# 6. PKCS#7 Bundle
echo "Test" > "$DATA_DIR/message.txt"
openssl crl2pkcs7 -nocrl -certfile "$DATA_DIR/ca.crt" -out "$DATA_DIR/bundle.p7b"

# 7. CMS Signed Data
openssl cms -sign -in "$DATA_DIR/message.txt" -signer "$DATA_DIR/ca.crt" -inkey "$DATA_DIR/key.pem" -outform DER -out "$DATA_DIR/signed.cms" -nodetach

# 8. CMS Encrypted Data
openssl cms -encrypt -in "$DATA_DIR/message.txt" -recip "$DATA_DIR/ca.crt" -outform DER -out "$DATA_DIR/encrypted.cms"

# 9. Public Key
openssl rsa -in "$DATA_DIR/key.pem" -pubout -out "$DATA_DIR/pub.pem"

# Build Java runner
echo "Building Java..."
# Assuming we are in root, and gradle wrapper is in root/Languages/Java provided by finalize?
# Wait, finalize put build.gradle in Languages/Java/build.gradle
# But gradlew is in Languages/der-java/? Or do we need to copy it?
# Use system gradle or installed gradle?
# Check where gradlew is.
# der-java has gradlew.
# But we should rely on the build.gradle generated by JavaEmitter in Languages/Java.

cd Languages/Java
# Create wrapper if not exists or use gradle directly?
# Check if gradle is in path
if ! command -v gradle &> /dev/null; then
    echo "gradle not found. using ./der.java/gradlew"
    GRADLE_CMD="./der.java/gradlew"
else
    GRADLE_CMD="gradle"
fi

# Compile
$GRADLE_CMD build -x test

# Run Tests
function run_java_test() {
    TYPE=$1
    FILE=$2
    echo "--- Testing $TYPE ($FILE) ---"
    # Execute class using gradle run or java -cp
    # Gradle run is easiest if Application plugin is set up, but we want to pass args.
    # ./gradlew run --args="..."
    $GRADLE_CMD runOpenSSLTest --quiet --args="$TYPE $PWD/../../$FILE"
}

run_java_test "pkcs8_private_key" "$DATA_DIR/pkcs8_key.pem"
run_java_test "pkcs8_public_key" "$DATA_DIR/pub.pem"
run_java_test "csr" "$DATA_DIR/csr.pem"
run_java_test "ca_cert" "$DATA_DIR/ca.crt"
run_java_test "ee_cert" "$DATA_DIR/ee.crt"
run_java_test "extended_cert" "$DATA_DIR/extended.crt"
run_java_test "pkcs7_bundle" "$DATA_DIR/bundle.p7b"
run_java_test "cms_signed" "$DATA_DIR/signed.cms"
run_java_test "cms_encrypted" "$DATA_DIR/encrypted.cms"

echo "ALL JAVA TESTS PASSED"
