// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Foundation

@usableFromInline struct ModifyRequest_changes_Sequence: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var operation: ModifyRequest_changes_Sequence_operation_Enum
    @usableFromInline var modification: PartialAttribute
    @inlinable init(operation: ModifyRequest_changes_Sequence_operation_Enum, modification: PartialAttribute) {
        self.operation = operation
        self.modification = modification
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let operation: ModifyRequest_changes_Sequence_operation_Enum = try ModifyRequest_changes_Sequence_operation_Enum(derEncoded: &nodes)
            let modification: PartialAttribute = try PartialAttribute(derEncoded: &nodes)
            return ModifyRequest_changes_Sequence(operation: operation, modification: modification)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(operation)
            try coder.serialize(modification)
        }
    }
}
