// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
import SwiftASN1
import Crypto
import Foundation

@usableFromInline struct SaslCredentials: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var mechanism: ASN1OctetString
    @usableFromInline var credentials: ASN1OctetString?
    @inlinable init(mechanism: ASN1OctetString, credentials: ASN1OctetString?) {
        self.mechanism = mechanism
        self.credentials = credentials
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let mechanism: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let credentials: ASN1OctetString? = try ASN1OctetString(derEncoded: &nodes)
            return SaslCredentials(mechanism: mechanism, credentials: credentials)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(mechanism)
            if let credentials = self.credentials { try coder.serialize(credentials) }
        }
    }
}
