// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023 Namdak Tonpa.
public struct V_version_IntEnum : Hashable, Sendable, Comparable {
    @usableFromInline  var rawValue: Int
    @inlinable public static func < (lhs: V_version_IntEnum, rhs: V_version_IntEnum) -> Bool { lhs.rawValue < rhs.rawValue }
    @inlinable init(rawValue: Int) { self.rawValue = rawValue }
    public static let v1 = Self(rawValue: 1)
}
