// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let ANSI_X9_62_ecdsa_with_Sha256: ASN1ObjectIdentifier = ANSI_X9_62_ecdsa_with_Specified + [2]
