// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct ANSI_X9_62_SpecifiedECDomainVersion : DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable, Comparable {
    public static var defaultIdentifier: ASN1Identifier { .integer }
    @usableFromInline  var rawValue: Int
    @inlinable public static func < (lhs: ANSI_X9_62_SpecifiedECDomainVersion, rhs: ANSI_X9_62_SpecifiedECDomainVersion) -> Bool { lhs.rawValue < rhs.rawValue }
    @inlinable init(rawValue: Int) { self.rawValue = rawValue }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try Int(derEncoded: rootNode, withIdentifier: identifier)
    }
    @inlinable public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    public static let ecdpVer1 = Self(rawValue: 1)
    public static let ecdpVer2 = Self(rawValue: 2)
    public static let ecdpVer3 = Self(rawValue: 3)
}
