// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let AuthenticationFramework_id_at_authorityRevocationList: ASN1ObjectIdentifier = UsefulDefinitions_id_at + [38]
