// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct AuthenticationFramework_AttCertValidityPeriod: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var notBeforeTime: GeneralizedTime
    @usableFromInline var notAfterTime: GeneralizedTime
    @inlinable init(notBeforeTime: GeneralizedTime, notAfterTime: GeneralizedTime) {
        self.notBeforeTime = notBeforeTime
        self.notAfterTime = notAfterTime

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let notBeforeTime: GeneralizedTime = try GeneralizedTime(derEncoded: &nodes)
            let notAfterTime: GeneralizedTime = try GeneralizedTime(derEncoded: &nodes)

            return AuthenticationFramework_AttCertValidityPeriod(notBeforeTime: notBeforeTime, notAfterTime: notAfterTime)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(notBeforeTime)
            try coder.serialize(notAfterTime)

        }
    }
}
