// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct BasicAccessControl_UserClasses: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var allUsers: ASN1Null?
    @usableFromInline var thisEntry: ASN1Null?
    @usableFromInline var name: [SelectedAttributeTypes_NameAndOptionalUID]?
    @usableFromInline var userGroup: [SelectedAttributeTypes_NameAndOptionalUID]?
    @usableFromInline var subtree: [InformationFramework_SubtreeSpecification]?
    @inlinable init(allUsers: ASN1Null?, thisEntry: ASN1Null?, name: [SelectedAttributeTypes_NameAndOptionalUID]?, userGroup: [SelectedAttributeTypes_NameAndOptionalUID]?, subtree: [InformationFramework_SubtreeSpecification]?) {
        self.allUsers = allUsers
        self.thisEntry = thisEntry
        self.name = name
        self.userGroup = userGroup
        self.subtree = subtree
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let allUsers: ASN1Null? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in return try ASN1Null(derEncoded: node) }
            let thisEntry: ASN1Null? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in return try ASN1Null(derEncoded: node) }
            let name: [SelectedAttributeTypes_NameAndOptionalUID]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 2, tagClass: .contextSpecific) { node in try DER.set(of: SelectedAttributeTypes_NameAndOptionalUID.self, identifier: .set, rootNode: node) }
            let userGroup: [SelectedAttributeTypes_NameAndOptionalUID]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 3, tagClass: .contextSpecific) { node in try DER.set(of: SelectedAttributeTypes_NameAndOptionalUID.self, identifier: .set, rootNode: node) }
            let subtree: [InformationFramework_SubtreeSpecification]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 4, tagClass: .contextSpecific) { node in try DER.set(of: InformationFramework_SubtreeSpecification.self, identifier: .set, rootNode: node) }
            return BasicAccessControl_UserClasses(allUsers: allUsers, thisEntry: thisEntry, name: name, userGroup: userGroup, subtree: subtree)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let allUsers = self.allUsers { if let allUsers = self.allUsers { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serialize(allUsers) } } }
            if let thisEntry = self.thisEntry { if let thisEntry = self.thisEntry { try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serialize(thisEntry) } } }
            if let name = self.name { if let name = self.name { try coder.serialize(explicitlyTaggedWithTagNumber: 2, tagClass: .contextSpecific) { codec in try codec.serializeSetOf(name) } } }
            if let userGroup = self.userGroup { if let userGroup = self.userGroup { try coder.serialize(explicitlyTaggedWithTagNumber: 3, tagClass: .contextSpecific) { codec in try codec.serializeSetOf(userGroup) } } }
            if let subtree = self.subtree { if let subtree = self.subtree { try coder.serialize(explicitlyTaggedWithTagNumber: 4, tagClass: .contextSpecific) { codec in try codec.serializeSetOf(subtree) } } }
        }
    }
}
