// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CertificateExtensions_PolicyInformation: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var policyIdentifier: CertificateExtensions_CertPolicyId
    @usableFromInline var policyQualifiers: [CertificateExtensions_PolicyQualifierInfo]?
    @inlinable init(policyIdentifier: CertificateExtensions_CertPolicyId, policyQualifiers: [CertificateExtensions_PolicyQualifierInfo]?) {
        self.policyIdentifier = policyIdentifier
        self.policyQualifiers = policyQualifiers

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let policyIdentifier: CertificateExtensions_CertPolicyId = try CertificateExtensions_CertPolicyId(derEncoded: &nodes)
            let policyQualifiers: [CertificateExtensions_PolicyQualifierInfo]? = try DER.sequence(of: CertificateExtensions_PolicyQualifierInfo.self, identifier: .sequence, nodes: &nodes)

            return CertificateExtensions_PolicyInformation(policyIdentifier: policyIdentifier, policyQualifiers: policyQualifiers)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(policyIdentifier)
            if let policyQualifiers = self.policyQualifiers { try coder.serializeSequenceOf(policyQualifiers) }

        }
    }
}
