// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CertificateExtensions_CertificatePairAssertion: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var forwardAssertion: CertificateExtensions_CertificateAssertion?
    @usableFromInline var reverseAssertion: CertificateExtensions_CertificateAssertion?
    @inlinable init(forwardAssertion: CertificateExtensions_CertificateAssertion?, reverseAssertion: CertificateExtensions_CertificateAssertion?) {
        self.forwardAssertion = forwardAssertion
        self.reverseAssertion = reverseAssertion

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let forwardAssertion: CertificateExtensions_CertificateAssertion? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let reverseAssertion: CertificateExtensions_CertificateAssertion? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))

            return CertificateExtensions_CertificatePairAssertion(forwardAssertion: forwardAssertion, reverseAssertion: reverseAssertion)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let forwardAssertion = self.forwardAssertion { try coder.serializeOptionalImplicitlyTagged(forwardAssertion, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            if let reverseAssertion = self.reverseAssertion { try coder.serializeOptionalImplicitlyTagged(reverseAssertion, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }

        }
    }
}
