// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CertificateExtensions_PolicyConstraintsSyntax: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var requireExplicitPolicy: CertificateExtensions_SkipCerts?
    @usableFromInline var inhibitPolicyMapping: CertificateExtensions_SkipCerts?
    @inlinable init(requireExplicitPolicy: CertificateExtensions_SkipCerts?, inhibitPolicyMapping: CertificateExtensions_SkipCerts?) {
        self.requireExplicitPolicy = requireExplicitPolicy
        self.inhibitPolicyMapping = inhibitPolicyMapping

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let requireExplicitPolicy: CertificateExtensions_SkipCerts? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let inhibitPolicyMapping: CertificateExtensions_SkipCerts? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))

            return CertificateExtensions_PolicyConstraintsSyntax(requireExplicitPolicy: requireExplicitPolicy, inhibitPolicyMapping: inhibitPolicyMapping)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let requireExplicitPolicy = self.requireExplicitPolicy { try coder.serializeOptionalImplicitlyTagged(requireExplicitPolicy, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            if let inhibitPolicyMapping = self.inhibitPolicyMapping { try coder.serializeOptionalImplicitlyTagged(inhibitPolicyMapping, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }

        }
    }
}
