// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let CertificateExtensions_id_ce_subjectKeyIdentifier: ASN1ObjectIdentifier = UsefulDefinitions_id_ce + [14]
