// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let CMSAesRsaesOaep_2009_id_aes128_wrap: ASN1ObjectIdentifier = CMSAesRsaesOaep_2009_aes + [5]
