// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let CMSECDHAlgs_2017_dhSinglePass_stdDH_hkdf_sha384_scheme: ASN1ObjectIdentifier = [20]
