// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Colour_Attributes_Colour_Space: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var colour_space_id: ArraySlice<UInt8>
    @usableFromInline var colour_space_type: Colour_Attributes_Colour_Space_Type
    @usableFromInline var colour_space_name: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var colour_data_scaling: Colour_Attributes_Colour_Data_Scaling?
    @usableFromInline var calibration_data: Colour_Attributes_Calibration_Data?
    @inlinable init(colour_space_id: ArraySlice<UInt8>, colour_space_type: Colour_Attributes_Colour_Space_Type, colour_space_name: Document_Profile_Descriptor_Character_Data?, colour_data_scaling: Colour_Attributes_Colour_Data_Scaling?, calibration_data: Colour_Attributes_Calibration_Data?) {
        self.colour_space_id = colour_space_id
        self.colour_space_type = colour_space_type
        self.colour_space_name = colour_space_name
        self.colour_data_scaling = colour_data_scaling
        self.calibration_data = calibration_data

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let colour_space_id: ArraySlice<UInt8> = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)))!
            let colour_space_type: Colour_Attributes_Colour_Space_Type = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)))!
            let colour_space_name: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let colour_data_scaling: Colour_Attributes_Colour_Data_Scaling? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 3, tagClass: .contextSpecific) { node in return try Colour_Attributes_Colour_Data_Scaling(derEncoded: node) }
            let calibration_data: Colour_Attributes_Calibration_Data? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 4, tagClass: .contextSpecific) { node in return try Colour_Attributes_Calibration_Data(derEncoded: node) }

            return Colour_Attributes_Colour_Space(colour_space_id: colour_space_id, colour_space_type: colour_space_type, colour_space_name: colour_space_name, colour_data_scaling: colour_data_scaling, calibration_data: calibration_data)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serializeOptionalImplicitlyTagged(colour_space_id, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            try coder.serializeOptionalImplicitlyTagged(colour_space_type, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            if let colour_space_name = self.colour_space_name { try coder.serializeOptionalImplicitlyTagged(colour_space_name, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) }
            if let colour_data_scaling = self.colour_data_scaling { try coder.serialize(explicitlyTaggedWithTagNumber: 3, tagClass: .contextSpecific) { codec in try codec.serialize(colour_data_scaling) } }
            if let calibration_data = self.calibration_data { try coder.serialize(explicitlyTaggedWithTagNumber: 4, tagClass: .contextSpecific) { codec in try codec.serialize(calibration_data) } }

        }
    }
}
