// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CryptographicMessageSyntax_2010_KeyTransRecipientInfo: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: CryptographicMessageSyntax_2010_CMSVersion
    @usableFromInline var rid: CryptographicMessageSyntax_2010_RecipientIdentifier
    @usableFromInline var keyEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier
    @usableFromInline var encryptedKey: CryptographicMessageSyntax_2010_EncryptedKey
    @inlinable init(version: CryptographicMessageSyntax_2010_CMSVersion, rid: CryptographicMessageSyntax_2010_RecipientIdentifier, keyEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier, encryptedKey: CryptographicMessageSyntax_2010_EncryptedKey) {
        self.version = version
        self.rid = rid
        self.keyEncryptionAlgorithm = keyEncryptionAlgorithm
        self.encryptedKey = encryptedKey

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let version: CryptographicMessageSyntax_2010_CMSVersion = try CryptographicMessageSyntax_2010_CMSVersion(derEncoded: &nodes)
            let rid: CryptographicMessageSyntax_2010_RecipientIdentifier = try CryptographicMessageSyntax_2010_RecipientIdentifier(derEncoded: &nodes)
            let keyEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier = try AuthenticationFramework_AlgorithmIdentifier(derEncoded: &nodes)
            let encryptedKey: CryptographicMessageSyntax_2010_EncryptedKey = try CryptographicMessageSyntax_2010_EncryptedKey(derEncoded: &nodes)

            return CryptographicMessageSyntax_2010_KeyTransRecipientInfo(version: version, rid: rid, keyEncryptionAlgorithm: keyEncryptionAlgorithm, encryptedKey: encryptedKey)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(version)
            try coder.serialize(rid)
            try coder.serialize(keyEncryptionAlgorithm)
            try coder.serialize(encryptedKey)

        }
    }
}
