// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline typealias CryptographicMessageSyntax_2009_Countersignature = CryptographicMessageSyntax_2009_SignerInfo
