// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var salt: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params_salt_Choice
    @usableFromInline var iterationCount: ArraySlice<UInt8>
    @usableFromInline var keyLength: ArraySlice<UInt8>?
    @usableFromInline var prf: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_PRFsAlgorithmIdentifier?
    @inlinable init(salt: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params_salt_Choice, iterationCount: ArraySlice<UInt8>, keyLength: ArraySlice<UInt8>?, prf: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_PRFsAlgorithmIdentifier?) {
        self.salt = salt
        self.iterationCount = iterationCount
        self.keyLength = keyLength
        self.prf = prf
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let salt: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params_salt_Choice = try CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params_salt_Choice(derEncoded: &nodes)
            let iterationCount: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let keyLength: ArraySlice<UInt8>? = try ArraySlice<UInt8>(derEncoded: &nodes)
            let prf: CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_PRFsAlgorithmIdentifier? = try CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_PRFsAlgorithmIdentifier(derEncoded: &nodes)
            return CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_params(salt: salt, iterationCount: iterationCount, keyLength: keyLength, prf: prf)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(salt)
            try coder.serialize(iterationCount)
            if let keyLength = self.keyLength { if let keyLength = self.keyLength { try coder.serialize(keyLength) } }
            if let prf = self.prf { if let prf = self.prf { try coder.serialize(prf) } }
        }
    }
}
