// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CryptographicMessageSyntax_2010_EncryptedContentInfo: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var contentType: ASN1ObjectIdentifier
    @usableFromInline var contentEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier
    @usableFromInline var encryptedContent: ASN1OctetString?
    @inlinable init(contentType: ASN1ObjectIdentifier, contentEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier, encryptedContent: ASN1OctetString?) {
        self.contentType = contentType
        self.contentEncryptionAlgorithm = contentEncryptionAlgorithm
        self.encryptedContent = encryptedContent

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let contentType: ASN1ObjectIdentifier = try ASN1ObjectIdentifier(derEncoded: &nodes)
            let contentEncryptionAlgorithm: AuthenticationFramework_AlgorithmIdentifier = try AuthenticationFramework_AlgorithmIdentifier(derEncoded: &nodes)
            let encryptedContent: ASN1OctetString? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))

            return CryptographicMessageSyntax_2010_EncryptedContentInfo(contentType: contentType, contentEncryptionAlgorithm: contentEncryptionAlgorithm, encryptedContent: encryptedContent)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(contentType)
            try coder.serialize(contentEncryptionAlgorithm)
            if let encryptedContent = self.encryptedContent { try coder.serializeOptionalImplicitlyTagged(encryptedContent, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }

        }
    }
}
