// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CryptographicMessageSyntax_2009_EnvelopedData: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: CryptographicMessageSyntax_2009_CMSVersion
    @usableFromInline var originatorInfo: CryptographicMessageSyntax_2009_OriginatorInfo?
    @usableFromInline var recipientInfos: CryptographicMessageSyntax_2009_RecipientInfos
    @usableFromInline var encryptedContentInfo: CryptographicMessageSyntax_2009_EncryptedContentInfo
    @usableFromInline var unprotectedAttrs: CryptographicMessageSyntax_2009_Attributes?
    @inlinable init(version: CryptographicMessageSyntax_2009_CMSVersion, originatorInfo: CryptographicMessageSyntax_2009_OriginatorInfo?, recipientInfos: CryptographicMessageSyntax_2009_RecipientInfos, encryptedContentInfo: CryptographicMessageSyntax_2009_EncryptedContentInfo, unprotectedAttrs: CryptographicMessageSyntax_2009_Attributes?) {
        self.version = version
        self.originatorInfo = originatorInfo
        self.recipientInfos = recipientInfos
        self.encryptedContentInfo = encryptedContentInfo
        self.unprotectedAttrs = unprotectedAttrs

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let version: CryptographicMessageSyntax_2009_CMSVersion = try CryptographicMessageSyntax_2009_CMSVersion(derEncoded: &nodes)
            let originatorInfo: CryptographicMessageSyntax_2009_OriginatorInfo? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let recipientInfos: CryptographicMessageSyntax_2009_RecipientInfos = try CryptographicMessageSyntax_2009_RecipientInfos(derEncoded: &nodes)
            let encryptedContentInfo: CryptographicMessageSyntax_2009_EncryptedContentInfo = try CryptographicMessageSyntax_2009_EncryptedContentInfo(derEncoded: &nodes)
            let unprotectedAttrs: CryptographicMessageSyntax_2009_Attributes? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))

            return CryptographicMessageSyntax_2009_EnvelopedData(version: version, originatorInfo: originatorInfo, recipientInfos: recipientInfos, encryptedContentInfo: encryptedContentInfo, unprotectedAttrs: unprotectedAttrs)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(version)
            if let originatorInfo = self.originatorInfo { try coder.serializeOptionalImplicitlyTagged(originatorInfo, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            try coder.serialize(recipientInfos)
            try coder.serialize(encryptedContentInfo)
            if let unprotectedAttrs = self.unprotectedAttrs { try coder.serializeOptionalImplicitlyTagged(unprotectedAttrs, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }

        }
    }
}
