// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let CryptographicMessageSyntaxAlgorithms_2009_id_gost28147_cfb: ASN1ObjectIdentifier = [1, 2, 804, 2, 1, 1, 1, 1, 1, 1, 3]
