// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CryptographicMessageSyntax_2010_DigestedData: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: CryptographicMessageSyntax_2010_CMSVersion
    @usableFromInline var digestAlgorithm: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier
    @usableFromInline var encapContentInfo: CryptographicMessageSyntax_2010_EncapsulatedContentInfo
    @usableFromInline var digest: CryptographicMessageSyntax_2010_Digest
    @inlinable init(version: CryptographicMessageSyntax_2010_CMSVersion, digestAlgorithm: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier, encapContentInfo: CryptographicMessageSyntax_2010_EncapsulatedContentInfo, digest: CryptographicMessageSyntax_2010_Digest) {
        self.version = version
        self.digestAlgorithm = digestAlgorithm
        self.encapContentInfo = encapContentInfo
        self.digest = digest

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let version: CryptographicMessageSyntax_2010_CMSVersion = try CryptographicMessageSyntax_2010_CMSVersion(derEncoded: &nodes)
            let digestAlgorithm: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier = try CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier(derEncoded: &nodes)
            let encapContentInfo: CryptographicMessageSyntax_2010_EncapsulatedContentInfo = try CryptographicMessageSyntax_2010_EncapsulatedContentInfo(derEncoded: &nodes)
            let digest: CryptographicMessageSyntax_2010_Digest = try CryptographicMessageSyntax_2010_Digest(derEncoded: &nodes)

            return CryptographicMessageSyntax_2010_DigestedData(version: version, digestAlgorithm: digestAlgorithm, encapContentInfo: encapContentInfo, digest: digest)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(version)
            try coder.serialize(digestAlgorithm)
            try coder.serialize(encapContentInfo)
            try coder.serialize(digest)

        }
    }
}
