// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Default_Value_Lists_Logical: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var composite_logical_attributes: Default_Value_Lists_Composite_Logical_Attributes?
    @usableFromInline var basic_logical_attributes: Default_Value_Lists_Basic_Logical_Attributes?
    @inlinable init(composite_logical_attributes: Default_Value_Lists_Composite_Logical_Attributes?, basic_logical_attributes: Default_Value_Lists_Basic_Logical_Attributes?) {
        self.composite_logical_attributes = composite_logical_attributes
        self.basic_logical_attributes = basic_logical_attributes

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let composite_logical_attributes: Default_Value_Lists_Composite_Logical_Attributes? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific))
            let basic_logical_attributes: Default_Value_Lists_Basic_Logical_Attributes? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific))

            return Default_Value_Lists_Logical(composite_logical_attributes: composite_logical_attributes, basic_logical_attributes: basic_logical_attributes)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let composite_logical_attributes = self.composite_logical_attributes { try coder.serializeOptionalImplicitlyTagged(composite_logical_attributes, withIdentifier: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific)) }
            if let basic_logical_attributes = self.basic_logical_attributes { try coder.serializeOptionalImplicitlyTagged(basic_logical_attributes, withIdentifier: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific)) }

        }
    }
}
