// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum DirectoryAbstractService_Code: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case local(ArraySlice<UInt8>)
    case global(ASN1ObjectIdentifier)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ArraySlice<UInt8>.defaultIdentifier:
                self = .local(try ArraySlice<UInt8>(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1ObjectIdentifier.defaultIdentifier:
                self = .global(try ASN1ObjectIdentifier(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .local(let local):
                            if identifier != Self.defaultIdentifier {
                                try coder.appendConstructedNode(identifier: identifier) { coder in
                                    try coder.serialize(local)
                                }
                            } else {
                                try coder.serialize(local)
                            }
            case .global(let global):
                            if identifier != Self.defaultIdentifier {
                                try coder.appendConstructedNode(identifier: identifier) { coder in
                                    try coder.serialize(global)
                                }
                            } else {
                                try coder.serialize(global)
                            }
        }
    }

}
