// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum DirectoryAbstractService_EntryInformationSelection_extraAttributes_Choice: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case allOperationalAttributes(ASN1Null)
    case select([PKIX1Explicit88_AttributeType])
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
                self = .allOperationalAttributes(try ASN1Null(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific):
                self = .select(try DER.set(of: PKIX1Explicit88_AttributeType.self, identifier: rootNode.identifier, rootNode: rootNode))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .allOperationalAttributes(let allOperationalAttributes): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) { coder in try allOperationalAttributes.serialize(into: &coder) }
            case .select(let select): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) { coder in try coder.serializeSetOf(select) }
        }
    }

}
