// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Document_Profile_Descriptor_Key_Information: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var method_information: Document_Profile_Descriptor_Method_Information?
    @usableFromInline var additional_information: Document_Profile_Descriptor_Additional_Information?
    @inlinable init(method_information: Document_Profile_Descriptor_Method_Information?, additional_information: Document_Profile_Descriptor_Additional_Information?) {
        self.method_information = method_information
        self.additional_information = additional_information

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let method_information: Document_Profile_Descriptor_Method_Information? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let additional_information: Document_Profile_Descriptor_Additional_Information? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))

            return Document_Profile_Descriptor_Key_Information(method_information: method_information, additional_information: additional_information)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let method_information = self.method_information { try coder.serializeOptionalImplicitlyTagged(method_information, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            if let additional_information = self.additional_information { try coder.serializeOptionalImplicitlyTagged(additional_information, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }

        }
    }
}
