// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Document_Profile_Descriptor_Security_Information: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var authorization: Document_Profile_Descriptor_Security_Information_authorization_Choice?
    @usableFromInline var security_classification: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var access_rights: [Document_Profile_Descriptor_Character_Data]?
    @inlinable init(authorization: Document_Profile_Descriptor_Security_Information_authorization_Choice?, security_classification: Document_Profile_Descriptor_Character_Data?, access_rights: [Document_Profile_Descriptor_Character_Data]?) {
        self.authorization = authorization
        self.security_classification = security_classification
        self.access_rights = access_rights

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            var authorization: Document_Profile_Descriptor_Security_Information_authorization_Choice? = nil
var peek_authorization = nodes
if let next = peek_authorization.next(), next.identifier == Document_Profile_Descriptor_Security_Information_authorization_Choice.defaultIdentifier {
    authorization = try Document_Profile_Descriptor_Security_Information_authorization_Choice(derEncoded: &nodes)
}
            let security_classification: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let access_rights: [Document_Profile_Descriptor_Character_Data]? = try DER.optionalImplicitlyTagged(&nodes, tagNumber: 2, tagClass: .contextSpecific) { node in try DER.set(of: Document_Profile_Descriptor_Character_Data.self, identifier: node.identifier, rootNode: node) }

            return Document_Profile_Descriptor_Security_Information(authorization: authorization, security_classification: security_classification, access_rights: access_rights)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let authorization = self.authorization { try coder.serialize(authorization) }
            if let security_classification = self.security_classification { try coder.serializeOptionalImplicitlyTagged(security_classification, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }
            if let access_rights = self.access_rights { try coder.serializeSetOf(access_rights, identifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) }

        }
    }
}
