// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Document_Profile_Descriptor_Sealed_Doc_Bodyparts: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var value: [Document_Profile_Descriptor_Sealed_Doc_Bodyparts_Element]
    @inlinable public init(_ value: [Document_Profile_Descriptor_Sealed_Doc_Bodyparts_Element]) { self.value = value }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.value = try DER.set(of: Document_Profile_Descriptor_Sealed_Doc_Bodyparts_Element.self, identifier: identifier, rootNode: rootNode)
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try coder.serializeSetOf(value, identifier: identifier)
    }
}
