// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct EnrollmentMessageSyntax_2009_CMCStatusInfo: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var cMCStatus: EnrollmentMessageSyntax_2009_CMCStatus
    @usableFromInline var bodyList: [EnrollmentMessageSyntax_2009_BodyPartID]
    @usableFromInline var statusString: ASN1UTF8String?
    @usableFromInline var otherInfo: EnrollmentMessageSyntax_2009_CMCStatusInfo_otherInfo_Choice?
    @inlinable init(cMCStatus: EnrollmentMessageSyntax_2009_CMCStatus, bodyList: [EnrollmentMessageSyntax_2009_BodyPartID], statusString: ASN1UTF8String?, otherInfo: EnrollmentMessageSyntax_2009_CMCStatusInfo_otherInfo_Choice?) {
        self.cMCStatus = cMCStatus
        self.bodyList = bodyList
        self.statusString = statusString
        self.otherInfo = otherInfo
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let cMCStatus: EnrollmentMessageSyntax_2009_CMCStatus = try EnrollmentMessageSyntax_2009_CMCStatus(derEncoded: &nodes)
            let bodyList: [EnrollmentMessageSyntax_2009_BodyPartID] = try DER.sequence(of: EnrollmentMessageSyntax_2009_BodyPartID.self, identifier: .sequence, nodes: &nodes)
            var statusString: ASN1UTF8String? = nil
var peek_statusString = nodes
if let next = peek_statusString.next(), next.identifier == ASN1UTF8String.defaultIdentifier {
    statusString = try ASN1UTF8String(derEncoded: &nodes)
}
            var otherInfo: EnrollmentMessageSyntax_2009_CMCStatusInfo_otherInfo_Choice? = nil
var peek_otherInfo = nodes
if let next = peek_otherInfo.next(), next.identifier == EnrollmentMessageSyntax_2009_CMCStatusInfo_otherInfo_Choice.defaultIdentifier {
    otherInfo = try EnrollmentMessageSyntax_2009_CMCStatusInfo_otherInfo_Choice(derEncoded: &nodes)
}
            return EnrollmentMessageSyntax_2009_CMCStatusInfo(cMCStatus: cMCStatus, bodyList: bodyList, statusString: statusString, otherInfo: otherInfo)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(cMCStatus)
            try coder.serializeSequenceOf(bodyList)
            if let statusString = self.statusString { if let statusString = self.statusString { try coder.serialize(statusString) } }
            if let otherInfo = self.otherInfo { if let otherInfo = self.otherInfo { try coder.serialize(otherInfo) } }
        }
    }
}
