// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct ExtendedSecurityServices_2009_MLData: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var mailListIdentifier: ExtendedSecurityServices_2009_EntityIdentifier
    @usableFromInline var expansionTime: GeneralizedTime
    @usableFromInline var mlReceiptPolicy: ExtendedSecurityServices_2009_MLReceiptPolicy?
    @inlinable init(mailListIdentifier: ExtendedSecurityServices_2009_EntityIdentifier, expansionTime: GeneralizedTime, mlReceiptPolicy: ExtendedSecurityServices_2009_MLReceiptPolicy?) {
        self.mailListIdentifier = mailListIdentifier
        self.expansionTime = expansionTime
        self.mlReceiptPolicy = mlReceiptPolicy
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let mailListIdentifier: ExtendedSecurityServices_2009_EntityIdentifier = try ExtendedSecurityServices_2009_EntityIdentifier(derEncoded: &nodes)
            let expansionTime: GeneralizedTime = try GeneralizedTime(derEncoded: &nodes)
            let mlReceiptPolicy: ExtendedSecurityServices_2009_MLReceiptPolicy? = try ExtendedSecurityServices_2009_MLReceiptPolicy(derEncoded: &nodes)
            return ExtendedSecurityServices_2009_MLData(mailListIdentifier: mailListIdentifier, expansionTime: expansionTime, mlReceiptPolicy: mlReceiptPolicy)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(mailListIdentifier)
            try coder.serialize(expansionTime)
            if let mlReceiptPolicy = self.mlReceiptPolicy { if let mlReceiptPolicy = self.mlReceiptPolicy { try coder.serialize(mlReceiptPolicy) } }
        }
    }
}
