// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct ExtendedSecurityServices_2009_ReceiptRequest: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var signedContentIdentifier: ExtendedSecurityServices_2009_ContentIdentifier
    @usableFromInline var receiptsFrom: ExtendedSecurityServices_2009_ReceiptsFrom
    @usableFromInline var receiptsTo: [CertificateExtensions_GeneralNames]
    @inlinable init(signedContentIdentifier: ExtendedSecurityServices_2009_ContentIdentifier, receiptsFrom: ExtendedSecurityServices_2009_ReceiptsFrom, receiptsTo: [CertificateExtensions_GeneralNames]) {
        self.signedContentIdentifier = signedContentIdentifier
        self.receiptsFrom = receiptsFrom
        self.receiptsTo = receiptsTo
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let signedContentIdentifier: ExtendedSecurityServices_2009_ContentIdentifier = try ExtendedSecurityServices_2009_ContentIdentifier(derEncoded: &nodes)
            let receiptsFrom: ExtendedSecurityServices_2009_ReceiptsFrom = try ExtendedSecurityServices_2009_ReceiptsFrom(derEncoded: &nodes)
            let receiptsTo: [CertificateExtensions_GeneralNames] = try DER.sequence(of: CertificateExtensions_GeneralNames.self, identifier: .sequence, nodes: &nodes)
            return ExtendedSecurityServices_2009_ReceiptRequest(signedContentIdentifier: signedContentIdentifier, receiptsFrom: receiptsFrom, receiptsTo: receiptsTo)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(signedContentIdentifier)
            try coder.serialize(receiptsFrom)
            try coder.serializeSequenceOf(receiptsTo)
        }
    }
}
