// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var fill_bundle_index: ArraySlice<UInt8>
    @usableFromInline var fill_bundle_representation: Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence_fill_bundle_representation_Sequence
    @inlinable init(fill_bundle_index: ArraySlice<UInt8>, fill_bundle_representation: Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence_fill_bundle_representation_Sequence) {
        self.fill_bundle_index = fill_bundle_index
        self.fill_bundle_representation = fill_bundle_representation
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let fill_bundle_index: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let fill_bundle_representation: Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence_fill_bundle_representation_Sequence = try Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence_fill_bundle_representation_Sequence(derEncoded: &nodes)
            return Geo_Gr_Presentation_Attributes_Filled_Area_Rendition_fill_bundle_specifications_Sequence(fill_bundle_index: fill_bundle_index, fill_bundle_representation: fill_bundle_representation)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(fill_bundle_index)
            try coder.serialize(fill_bundle_representation)
        }
    }
}
