// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct InformationFramework_MRMapping: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var mapping: [InformationFramework_Mapping]?
    @usableFromInline var substitution: [InformationFramework_MRSubstitution]?
    @inlinable init(mapping: [InformationFramework_Mapping]?, substitution: [InformationFramework_MRSubstitution]?) {
        self.mapping = mapping
        self.substitution = substitution

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let mapping: [InformationFramework_Mapping]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in try DER.sequence(of: InformationFramework_Mapping.self, identifier: .sequence, rootNode: node) }
            let substitution: [InformationFramework_MRSubstitution]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in try DER.sequence(of: InformationFramework_MRSubstitution.self, identifier: .sequence, rootNode: node) }

            return InformationFramework_MRMapping(mapping: mapping, substitution: substitution)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let mapping = self.mapping { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serializeSequenceOf(mapping) } }
            if let substitution = self.substitution { try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serializeSequenceOf(substitution) } }

        }
    }
}
