// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let InformationFramework_id_oc_parent: ASN1ObjectIdentifier = UsefulDefinitions_id_oc + [28]
