// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct InformationFramework_SubtreeSpecification: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var base: InformationFramework_LocalName?
    @usableFromInline var specificExclusions: [InformationFramework_ChopSpecification_specificExclusions_Choice]?
    @usableFromInline var minimum: InformationFramework_BaseDistance?
    @usableFromInline var maximum: InformationFramework_BaseDistance?
    @usableFromInline var specificationFilter: InformationFramework_Refinement?
    @inlinable init(base: InformationFramework_LocalName?, specificExclusions: [InformationFramework_ChopSpecification_specificExclusions_Choice]?, minimum: InformationFramework_BaseDistance?, maximum: InformationFramework_BaseDistance?, specificationFilter: InformationFramework_Refinement?) {
        self.base = base
        self.specificExclusions = specificExclusions
        self.minimum = minimum
        self.maximum = maximum
        self.specificationFilter = specificationFilter
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let base: InformationFramework_LocalName = try DER.explicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in return try InformationFramework_LocalName(derEncoded: node) }
            let specificExclusions: [InformationFramework_ChopSpecification_specificExclusions_Choice]? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in try DER.set(of: InformationFramework_ChopSpecification_specificExclusions_Choice.self, identifier: .set, rootNode: node) }
            let minimum: InformationFramework_BaseDistance = try DER.explicitlyTagged(&nodes, tagNumber: 2, tagClass: .contextSpecific) { node in return try InformationFramework_BaseDistance(derEncoded: node) }
            let maximum: InformationFramework_BaseDistance? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 3, tagClass: .contextSpecific) { node in return try InformationFramework_BaseDistance(derEncoded: node) }
            let specificationFilter: InformationFramework_Refinement? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 4, tagClass: .contextSpecific) { node in return try InformationFramework_Refinement(derEncoded: node) }
            return InformationFramework_SubtreeSpecification(base: base, specificExclusions: specificExclusions, minimum: minimum, maximum: maximum, specificationFilter: specificationFilter)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let base = self.base { if let base = self.base { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serialize(base) } } }
            if let specificExclusions = self.specificExclusions { if let specificExclusions = self.specificExclusions { try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serializeSetOf(specificExclusions) } } }
            if let minimum = self.minimum { if let minimum = self.minimum { try coder.serialize(explicitlyTaggedWithTagNumber: 2, tagClass: .contextSpecific) { codec in try codec.serialize(minimum) } } }
            if let maximum = self.maximum { if let maximum = self.maximum { try coder.serialize(explicitlyTaggedWithTagNumber: 3, tagClass: .contextSpecific) { codec in try codec.serialize(maximum) } } }
            if let specificationFilter = self.specificationFilter { if let specificationFilter = self.specificationFilter { try coder.serialize(explicitlyTaggedWithTagNumber: 4, tagClass: .contextSpecific) { codec in try codec.serialize(specificationFilter) } } }
        }
    }
}
