// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Vscript_Properties: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var iso_standard_9541_vsoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?
    @usableFromInline var iso_standard_9541_vsoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?
    @usableFromInline var iso_standard_9541_vsscalex: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational?
    @usableFromInline var iso_standard_9541_vsscaley: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational?
    @usableFromInline var non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List?
    @inlinable init(iso_standard_9541_vsoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?, iso_standard_9541_vsoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?, iso_standard_9541_vsscalex: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational?, iso_standard_9541_vsscaley: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational?, non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List?) {
        self.iso_standard_9541_vsoffsetx = iso_standard_9541_vsoffsetx
        self.iso_standard_9541_vsoffsety = iso_standard_9541_vsoffsety
        self.iso_standard_9541_vsscalex = iso_standard_9541_vsscalex
        self.iso_standard_9541_vsscaley = iso_standard_9541_vsscaley
        self.non_iso_properties = non_iso_properties
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let iso_standard_9541_vsoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let iso_standard_9541_vsoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let iso_standard_9541_vsscalex: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let iso_standard_9541_vsscaley: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            let non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific))
            return ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Vscript_Properties(iso_standard_9541_vsoffsetx: iso_standard_9541_vsoffsetx, iso_standard_9541_vsoffsety: iso_standard_9541_vsoffsety, iso_standard_9541_vsscalex: iso_standard_9541_vsscalex, iso_standard_9541_vsscaley: iso_standard_9541_vsscaley, non_iso_properties: non_iso_properties)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let iso_standard_9541_vsoffsetx = self.iso_standard_9541_vsoffsetx { if let iso_standard_9541_vsoffsetx = self.iso_standard_9541_vsoffsetx { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_vsoffsetx, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) } }
            if let iso_standard_9541_vsoffsety = self.iso_standard_9541_vsoffsety { if let iso_standard_9541_vsoffsety = self.iso_standard_9541_vsoffsety { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_vsoffsety, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) } }
            if let iso_standard_9541_vsscalex = self.iso_standard_9541_vsscalex { if let iso_standard_9541_vsscalex = self.iso_standard_9541_vsscalex { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_vsscalex, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) } }
            if let iso_standard_9541_vsscaley = self.iso_standard_9541_vsscaley { if let iso_standard_9541_vsscaley = self.iso_standard_9541_vsscaley { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_vsscaley, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) } }
            if let non_iso_properties = self.non_iso_properties { if let non_iso_properties = self.non_iso_properties { try coder.serializeOptionalImplicitlyTagged(non_iso_properties, withIdentifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) } }
        }
    }
}
