// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline typealias ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Angle = ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rational
