// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Score_Properties: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var iso_standard_9541_scoreoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?
    @usableFromInline var iso_standard_9541_scoreoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?
    @usableFromInline var iso_standard_9541_scorethick: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?
    @usableFromInline var non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List?
    @inlinable init(iso_standard_9541_scoreoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?, iso_standard_9541_scoreoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?, iso_standard_9541_scorethick: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational?, non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List?) {
        self.iso_standard_9541_scoreoffsetx = iso_standard_9541_scoreoffsetx
        self.iso_standard_9541_scoreoffsety = iso_standard_9541_scoreoffsety
        self.iso_standard_9541_scorethick = iso_standard_9541_scorethick
        self.non_iso_properties = non_iso_properties
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let iso_standard_9541_scoreoffsetx: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let iso_standard_9541_scoreoffsety: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let iso_standard_9541_scorethick: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Rel_Rational? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let non_iso_properties: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Property_List? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            return ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Score_Properties(iso_standard_9541_scoreoffsetx: iso_standard_9541_scoreoffsetx, iso_standard_9541_scoreoffsety: iso_standard_9541_scoreoffsety, iso_standard_9541_scorethick: iso_standard_9541_scorethick, non_iso_properties: non_iso_properties)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let iso_standard_9541_scoreoffsetx = self.iso_standard_9541_scoreoffsetx { if let iso_standard_9541_scoreoffsetx = self.iso_standard_9541_scoreoffsetx { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_scoreoffsetx, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) } }
            if let iso_standard_9541_scoreoffsety = self.iso_standard_9541_scoreoffsety { if let iso_standard_9541_scoreoffsety = self.iso_standard_9541_scoreoffsety { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_scoreoffsety, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) } }
            if let iso_standard_9541_scorethick = self.iso_standard_9541_scorethick { if let iso_standard_9541_scorethick = self.iso_standard_9541_scorethick { try coder.serializeOptionalImplicitlyTagged(iso_standard_9541_scorethick, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) } }
            if let non_iso_properties = self.non_iso_properties { if let non_iso_properties = self.non_iso_properties { try coder.serializeOptionalImplicitlyTagged(non_iso_properties, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) } }
        }
    }
}
