// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Design_Group: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code
    @usableFromInline var subgroup_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code
    @usableFromInline var specific_group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code
    @inlinable init(group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code, subgroup_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code, specific_group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code) {
        self.group_code = group_code
        self.subgroup_code = subgroup_code
        self.specific_group_code = specific_group_code
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)))!
            let subgroup_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)))!
            let specific_group_code: ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Code = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)))!
            return ISO_STANDARD_9541_FONT_ATTRIBUTE_SET_Design_Group(group_code: group_code, subgroup_code: subgroup_code, specific_group_code: specific_group_code)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serializeOptionalImplicitlyTagged(group_code, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            try coder.serializeOptionalImplicitlyTagged(subgroup_code, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            try coder.serializeOptionalImplicitlyTagged(specific_group_code, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
        }
    }
}
