// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Layout_Descriptors_Border_Edge: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var line_width: ArraySlice<UInt8>?
    @usableFromInline var line_type: Layout_Descriptors_Border_Edge_line_type_IntEnum?
    @usableFromInline var freespace_width: ArraySlice<UInt8>?
    @usableFromInline var border_line_colour: Layout_Descriptors_Border_Line_Colour?
    @inlinable init(line_width: ArraySlice<UInt8>?, line_type: Layout_Descriptors_Border_Edge_line_type_IntEnum?, freespace_width: ArraySlice<UInt8>?, border_line_colour: Layout_Descriptors_Border_Line_Colour?) {
        self.line_width = line_width
        self.line_type = line_type
        self.freespace_width = freespace_width
        self.border_line_colour = border_line_colour
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let line_width: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let line_type = try Layout_Descriptors_Border_Edge_line_type_IntEnum(rawValue: Int(derEncoded: &nodes))
            let freespace_width: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let border_line_colour: Layout_Descriptors_Border_Line_Colour? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 3, tagClass: .contextSpecific) { node in return try Layout_Descriptors_Border_Line_Colour(derEncoded: node) }
            return Layout_Descriptors_Border_Edge(line_width: line_width, line_type: line_type, freespace_width: freespace_width, border_line_colour: border_line_colour)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let line_width = self.line_width { if let line_width = self.line_width { try coder.serializeOptionalImplicitlyTagged(line_width, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) } }
            if let line_type = self.line_type { try coder.serialize(line_type.rawValue, explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) }
            if let freespace_width = self.freespace_width { if let freespace_width = self.freespace_width { try coder.serializeOptionalImplicitlyTagged(freespace_width, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) } }
            if let border_line_colour = self.border_line_colour { if let border_line_colour = self.border_line_colour { try coder.serialize(explicitlyTaggedWithTagNumber: 3, tagClass: .contextSpecific) { codec in try codec.serialize(border_line_colour) } } }
        }
    }
}
