// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum Layout_Descriptors_Colour_Of_Medium: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case unspecified_colour(ASN1Null)
    case specified_colour(Colour_Attributes_Colour_Expression)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
        case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
            self = .unspecified_colour(try ASN1Null(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case Colour_Attributes_Colour_Expression.defaultIdentifier:
            self = .specified_colour(try Colour_Attributes_Colour_Expression(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
        case .unspecified_colour(let unspecified_colour): try unspecified_colour.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
        case .specified_colour(let specified_colour):
                        if identifier != Self.defaultIdentifier {
                            try coder.appendConstructedNode(identifier: identifier) { coder in
                                try coder.serialize(specified_colour)
                            }
                        } else {
                            try coder.serialize(specified_colour)
                        }

        }
    }

}
