// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct Layout_Descriptors_Layout_Object_Type : DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable, Comparable {
    public static var defaultIdentifier: ASN1Identifier { .integer }
    @usableFromInline  var rawValue: Int
    @inlinable public static func < (lhs: Layout_Descriptors_Layout_Object_Type, rhs: Layout_Descriptors_Layout_Object_Type) -> Bool { lhs.rawValue < rhs.rawValue }
    @inlinable init(rawValue: Int) { self.rawValue = rawValue }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try Int(derEncoded: rootNode, withIdentifier: identifier)
    }
    @inlinable public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    public static let document_layout_root = Self(rawValue: 0)
    public static let page_set = Self(rawValue: 1)
    public static let page = Self(rawValue: 2)
    public static let frame = Self(rawValue: 3)
    public static let block = Self(rawValue: 4)
}
