// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline typealias Location_Expressions_Subtree_Locator = Location_Expressions_Object_Locator
