// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public struct Logical_Descriptors_Protection : DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable, Comparable {
    public static var defaultIdentifier: ASN1Identifier { .integer }
    @usableFromInline  var rawValue: Int
    @inlinable public static func < (lhs: Logical_Descriptors_Protection, rhs: Logical_Descriptors_Protection) -> Bool { lhs.rawValue < rhs.rawValue }
    @inlinable init(rawValue: Int) { self.rawValue = rawValue }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.rawValue = try Int(derEncoded: rootNode, withIdentifier: identifier)
    }
    @inlinable public func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try self.rawValue.serialize(into: &coder, withIdentifier: identifier)
    }
    public static let unprotected = Self(rawValue: 0)
    public static let protected = Self(rawValue: 1)
}
