// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct MultipleSignatures_2010_MultipleSignatures: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var bodyHashAlg: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier
    @usableFromInline var signAlg: CryptographicMessageSyntax_2010_SignatureAlgorithmIdentifier
    @usableFromInline var signAttrsHash: MultipleSignatures_2010_SignAttrsHash
    @usableFromInline var cert: ExtendedSecurityServices_2009_ESSCertIDv2?
    @inlinable init(bodyHashAlg: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier, signAlg: CryptographicMessageSyntax_2010_SignatureAlgorithmIdentifier, signAttrsHash: MultipleSignatures_2010_SignAttrsHash, cert: ExtendedSecurityServices_2009_ESSCertIDv2?) {
        self.bodyHashAlg = bodyHashAlg
        self.signAlg = signAlg
        self.signAttrsHash = signAttrsHash
        self.cert = cert

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let bodyHashAlg: CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier = try CryptographicMessageSyntax_2010_DigestAlgorithmIdentifier(derEncoded: &nodes)
            let signAlg: CryptographicMessageSyntax_2010_SignatureAlgorithmIdentifier = try CryptographicMessageSyntax_2010_SignatureAlgorithmIdentifier(derEncoded: &nodes)
            let signAttrsHash: MultipleSignatures_2010_SignAttrsHash = try MultipleSignatures_2010_SignAttrsHash(derEncoded: &nodes)
            var cert: ExtendedSecurityServices_2009_ESSCertIDv2? = nil
var peek_cert = nodes
if let next = peek_cert.next(), next.identifier == ExtendedSecurityServices_2009_ESSCertIDv2.defaultIdentifier {
    cert = try ExtendedSecurityServices_2009_ESSCertIDv2(derEncoded: &nodes)
}

            return MultipleSignatures_2010_MultipleSignatures(bodyHashAlg: bodyHashAlg, signAlg: signAlg, signAttrsHash: signAttrsHash, cert: cert)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(bodyHashAlg)
            try coder.serialize(signAlg)
            try coder.serialize(signAttrsHash)
            if let cert = self.cert { try coder.serialize(cert) }

        }
    }
}
