// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let OCSP_id_pkix_ocsp_archive_cutoff: ASN1ObjectIdentifier = OCSP_id_pkix_ocsp + [6]
