// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum PKCS_7_SignerInfos: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case siSet([PKCS_7_SignerInfo])
    case siSequence([PKCS_7_SignerInfo])
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
        case ASN1Identifier.set:
            self = .siSet(try DER.set(of: PKCS_7_SignerInfo.self, identifier: .set, rootNode: rootNode))
        case ASN1Identifier.sequence:
            self = .siSequence(try DER.sequence(of: PKCS_7_SignerInfo.self, identifier: .sequence, rootNode: rootNode))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
        case .siSet(let siSet): try coder.serializeSetOf(siSet)
        case .siSequence(let siSequence): try coder.serializeSequenceOf(siSequence)

        }
    }

}
