// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKCS_9_SMIMECapability: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var algorithm: ASN1ObjectIdentifier
    @usableFromInline var parameters: ASN1Any
    @inlinable init(algorithm: ASN1ObjectIdentifier, parameters: ASN1Any) {
        self.algorithm = algorithm
        self.parameters = parameters
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let algorithm: ASN1ObjectIdentifier = try ASN1ObjectIdentifier(derEncoded: &nodes)
            let parameters: ASN1Any = try ASN1Any(derEncoded: &nodes)
            return PKCS_9_SMIMECapability(algorithm: algorithm, parameters: parameters)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(algorithm)
            try coder.serialize(parameters)
        }
    }
}
