// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum PKCS_5_PBKDF2_params_salt_Choice: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case specified(ASN1OctetString)
    case otherSource(AuthenticationFramework_AlgorithmIdentifier)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
        case ASN1OctetString.defaultIdentifier:
            self = .specified(try ASN1OctetString(derEncoded: rootNode, withIdentifier: rootNode.identifier))
        case AuthenticationFramework_AlgorithmIdentifier.defaultIdentifier:
            self = .otherSource(try AuthenticationFramework_AlgorithmIdentifier(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
        case .specified(let specified):
                        if identifier != Self.defaultIdentifier {
                            try coder.appendConstructedNode(identifier: identifier) { coder in
                                try coder.serialize(specified)
                            }
                        } else {
                            try coder.serialize(specified)
                        }
        case .otherSource(let otherSource):
                        if identifier != Self.defaultIdentifier {
                            try coder.appendConstructedNode(identifier: identifier) { coder in
                                try coder.serialize(otherSource)
                            }
                        } else {
                            try coder.serialize(otherSource)
                        }

        }
    }

}
