// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKCS_8_PrivateKeyInfo: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: PKCS_8_Version
    @usableFromInline var privateKeyAlgorithm: AuthenticationFramework_AlgorithmIdentifier
    @usableFromInline var privateKey: PKCS_8_PrivateKey
    @usableFromInline var attributes: PKCS_8_Attributes?
    @inlinable init(version: PKCS_8_Version, privateKeyAlgorithm: AuthenticationFramework_AlgorithmIdentifier, privateKey: PKCS_8_PrivateKey, attributes: PKCS_8_Attributes?) {
        self.version = version
        self.privateKeyAlgorithm = privateKeyAlgorithm
        self.privateKey = privateKey
        self.attributes = attributes

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let version: PKCS_8_Version = try PKCS_8_Version(derEncoded: &nodes)
            let privateKeyAlgorithm: AuthenticationFramework_AlgorithmIdentifier = try AuthenticationFramework_AlgorithmIdentifier(derEncoded: &nodes)
            let privateKey: PKCS_8_PrivateKey = try PKCS_8_PrivateKey(derEncoded: &nodes)
            let attributes: PKCS_8_Attributes? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))

            return PKCS_8_PrivateKeyInfo(version: version, privateKeyAlgorithm: privateKeyAlgorithm, privateKey: privateKey, attributes: attributes)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(version)
            try coder.serialize(privateKeyAlgorithm)
            try coder.serialize(privateKey)
            if let attributes = self.attributes { try coder.serializeOptionalImplicitlyTagged(attributes, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }

        }
    }
}
