// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let PKIXAttributeCertificate_2009_id_aca_accessIdentity: ASN1ObjectIdentifier = [2]
