// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline typealias PKIX1Explicit88_PhysicalDeliveryOfficeName = PKIX1Explicit88_PDSParameter
