// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIXAttributeCertificate_2009_ACClearAttrs: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var acIssuer: PKIX1Implicit88_GeneralName
    @usableFromInline var acSerial: ArraySlice<UInt8>
    @usableFromInline var attrs: [PKIX_CommonTypes_2009_AttributeSet]
    @inlinable init(acIssuer: PKIX1Implicit88_GeneralName, acSerial: ArraySlice<UInt8>, attrs: [PKIX_CommonTypes_2009_AttributeSet]) {
        self.acIssuer = acIssuer
        self.acSerial = acSerial
        self.attrs = attrs
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let acIssuer: PKIX1Implicit88_GeneralName = try PKIX1Implicit88_GeneralName(derEncoded: &nodes)
            let acSerial: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let attrs: [PKIX_CommonTypes_2009_AttributeSet] = try DER.sequence(of: PKIX_CommonTypes_2009_AttributeSet.self, identifier: .sequence, nodes: &nodes)
            return PKIXAttributeCertificate_2009_ACClearAttrs(acIssuer: acIssuer, acSerial: acSerial, attrs: attrs)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(acIssuer)
            try coder.serialize(acSerial)
            try coder.serializeSequenceOf(attrs)
        }
    }
}
