// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIXCMP_2009_CAKeyUpdAnnContent: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var oldWithNew: PKIXCMP_2009_CMPCertificate
    @usableFromInline var newWithOld: PKIXCMP_2009_CMPCertificate
    @usableFromInline var newWithNew: PKIXCMP_2009_CMPCertificate
    @inlinable init(oldWithNew: PKIXCMP_2009_CMPCertificate, newWithOld: PKIXCMP_2009_CMPCertificate, newWithNew: PKIXCMP_2009_CMPCertificate) {
        self.oldWithNew = oldWithNew
        self.newWithOld = newWithOld
        self.newWithNew = newWithNew
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let oldWithNew: PKIXCMP_2009_CMPCertificate = try PKIXCMP_2009_CMPCertificate(derEncoded: &nodes)
            let newWithOld: PKIXCMP_2009_CMPCertificate = try PKIXCMP_2009_CMPCertificate(derEncoded: &nodes)
            let newWithNew: PKIXCMP_2009_CMPCertificate = try PKIXCMP_2009_CMPCertificate(derEncoded: &nodes)
            return PKIXCMP_2009_CAKeyUpdAnnContent(oldWithNew: oldWithNew, newWithOld: newWithOld, newWithNew: newWithNew)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(oldWithNew)
            try coder.serialize(newWithOld)
            try coder.serialize(newWithNew)
        }
    }
}
