// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIX1Explicit88_CertificateList: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var tbsCertList: PKIX1Explicit88_TBSCertList
    @usableFromInline var signatureAlgorithm: PKIX1Explicit88_AlgorithmIdentifier
    @usableFromInline var signature: ASN1BitString
    @inlinable init(tbsCertList: PKIX1Explicit88_TBSCertList, signatureAlgorithm: PKIX1Explicit88_AlgorithmIdentifier, signature: ASN1BitString) {
        self.tbsCertList = tbsCertList
        self.signatureAlgorithm = signatureAlgorithm
        self.signature = signature
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let tbsCertList: PKIX1Explicit88_TBSCertList = try PKIX1Explicit88_TBSCertList(derEncoded: &nodes)
            let signatureAlgorithm: PKIX1Explicit88_AlgorithmIdentifier = try PKIX1Explicit88_AlgorithmIdentifier(derEncoded: &nodes)
            let signature: ASN1BitString = try ASN1BitString(derEncoded: &nodes)
            return PKIX1Explicit88_CertificateList(tbsCertList: tbsCertList, signatureAlgorithm: signatureAlgorithm, signature: signature)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(tbsCertList)
            try coder.serialize(signatureAlgorithm)
            try coder.serialize(signature)
        }
    }
}
