// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIXCMP_2009_OOBCertHash: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var hashAlg: PKIX1Explicit88_AlgorithmIdentifier?
    @usableFromInline var certId: PKIXCRMF_2009_CertId?
    @usableFromInline var hashVal: ASN1BitString
    @inlinable init(hashAlg: PKIX1Explicit88_AlgorithmIdentifier?, certId: PKIXCRMF_2009_CertId?, hashVal: ASN1BitString) {
        self.hashAlg = hashAlg
        self.certId = certId
        self.hashVal = hashVal

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let hashAlg: PKIX1Explicit88_AlgorithmIdentifier? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in return try PKIX1Explicit88_AlgorithmIdentifier(derEncoded: node) }
            let certId: PKIXCRMF_2009_CertId? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in return try PKIXCRMF_2009_CertId(derEncoded: node) }
            let hashVal: ASN1BitString = try ASN1BitString(derEncoded: &nodes)

            return PKIXCMP_2009_OOBCertHash(hashAlg: hashAlg, certId: certId, hashVal: hashVal)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let hashAlg = self.hashAlg { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serialize(hashAlg) } }
            if let certId = self.certId { try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serialize(certId) } }
            try coder.serialize(hashVal)

        }
    }
}
