// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIX1Explicit88_RDNSequence: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var value: [PKIX1Explicit88_RelativeDistinguishedName]
    @inlinable public init(_ value: [PKIX1Explicit88_RelativeDistinguishedName]) { self.value = value }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.value = try DER.sequence(of: PKIX1Explicit88_RelativeDistinguishedName.self, identifier: identifier, rootNode: rootNode)
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try coder.serializeSequenceOf(value, identifier: identifier)
    }
}
