// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIXCRMF_2009_EncryptedValue: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var intendedAlg: PKIX1Explicit88_AlgorithmIdentifier?
    @usableFromInline var symmAlg: PKIX1Explicit88_AlgorithmIdentifier?
    @usableFromInline var encSymmKey: ASN1BitString?
    @usableFromInline var keyAlg: PKIX1Explicit88_AlgorithmIdentifier?
    @usableFromInline var valueHint: ASN1OctetString?
    @usableFromInline var encValue: ASN1BitString
    @inlinable init(intendedAlg: PKIX1Explicit88_AlgorithmIdentifier?, symmAlg: PKIX1Explicit88_AlgorithmIdentifier?, encSymmKey: ASN1BitString?, keyAlg: PKIX1Explicit88_AlgorithmIdentifier?, valueHint: ASN1OctetString?, encValue: ASN1BitString) {
        self.intendedAlg = intendedAlg
        self.symmAlg = symmAlg
        self.encSymmKey = encSymmKey
        self.keyAlg = keyAlg
        self.valueHint = valueHint
        self.encValue = encValue

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let intendedAlg: PKIX1Explicit88_AlgorithmIdentifier? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let symmAlg: PKIX1Explicit88_AlgorithmIdentifier? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let encSymmKey: ASN1BitString? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let keyAlg: PKIX1Explicit88_AlgorithmIdentifier? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            let valueHint: ASN1OctetString? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific))
            let encValue: ASN1BitString = try ASN1BitString(derEncoded: &nodes)

            return PKIXCRMF_2009_EncryptedValue(intendedAlg: intendedAlg, symmAlg: symmAlg, encSymmKey: encSymmKey, keyAlg: keyAlg, valueHint: valueHint, encValue: encValue)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let intendedAlg = self.intendedAlg { try coder.serializeOptionalImplicitlyTagged(intendedAlg, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            if let symmAlg = self.symmAlg { try coder.serializeOptionalImplicitlyTagged(symmAlg, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }
            if let encSymmKey = self.encSymmKey { try coder.serializeOptionalImplicitlyTagged(encSymmKey, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) }
            if let keyAlg = self.keyAlg { try coder.serializeOptionalImplicitlyTagged(keyAlg, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) }
            if let valueHint = self.valueHint { try coder.serializeOptionalImplicitlyTagged(valueHint, withIdentifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) }
            try coder.serialize(encValue)

        }
    }
}
