// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct PKIXAttributeCertificate_2009_AttributeCertificateInfo: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: PKIXAttributeCertificate_2009_AttCertVersion
    @usableFromInline var holder: PKIXAttributeCertificate_2009_Holder
    @usableFromInline var issuer: PKIXAttributeCertificate_2009_AttCertIssuer
    @usableFromInline var signature: PKIX1Explicit88_AlgorithmIdentifier
    @usableFromInline var serialNumber: PKIX1Explicit88_CertificateSerialNumber
    @usableFromInline var attrCertValidityPeriod: PKIXAttributeCertificate_2009_AttCertValidityPeriod
    @usableFromInline var attributes: [PKIX_CommonTypes_2009_AttributeSet]
    @usableFromInline var issuerUniqueID: PKIX1Explicit88_UniqueIdentifier?
    @usableFromInline var extensions: PKIX1Explicit88_Extensions?
    @inlinable init(version: PKIXAttributeCertificate_2009_AttCertVersion, holder: PKIXAttributeCertificate_2009_Holder, issuer: PKIXAttributeCertificate_2009_AttCertIssuer, signature: PKIX1Explicit88_AlgorithmIdentifier, serialNumber: PKIX1Explicit88_CertificateSerialNumber, attrCertValidityPeriod: PKIXAttributeCertificate_2009_AttCertValidityPeriod, attributes: [PKIX_CommonTypes_2009_AttributeSet], issuerUniqueID: PKIX1Explicit88_UniqueIdentifier?, extensions: PKIX1Explicit88_Extensions?) {
        self.version = version
        self.holder = holder
        self.issuer = issuer
        self.signature = signature
        self.serialNumber = serialNumber
        self.attrCertValidityPeriod = attrCertValidityPeriod
        self.attributes = attributes
        self.issuerUniqueID = issuerUniqueID
        self.extensions = extensions
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let version: PKIXAttributeCertificate_2009_AttCertVersion = try PKIXAttributeCertificate_2009_AttCertVersion(derEncoded: &nodes)
            let holder: PKIXAttributeCertificate_2009_Holder = try PKIXAttributeCertificate_2009_Holder(derEncoded: &nodes)
            let issuer: PKIXAttributeCertificate_2009_AttCertIssuer = try PKIXAttributeCertificate_2009_AttCertIssuer(derEncoded: &nodes)
            let signature: PKIX1Explicit88_AlgorithmIdentifier = try PKIX1Explicit88_AlgorithmIdentifier(derEncoded: &nodes)
            let serialNumber: PKIX1Explicit88_CertificateSerialNumber = try PKIX1Explicit88_CertificateSerialNumber(derEncoded: &nodes)
            let attrCertValidityPeriod: PKIXAttributeCertificate_2009_AttCertValidityPeriod = try PKIXAttributeCertificate_2009_AttCertValidityPeriod(derEncoded: &nodes)
            let attributes: [PKIX_CommonTypes_2009_AttributeSet] = try DER.sequence(of: PKIX_CommonTypes_2009_AttributeSet.self, identifier: .sequence, nodes: &nodes)
            let issuerUniqueID: PKIX1Explicit88_UniqueIdentifier? = try PKIX1Explicit88_UniqueIdentifier(derEncoded: &nodes)
            let extensions: PKIX1Explicit88_Extensions? = try PKIX1Explicit88_Extensions(derEncoded: &nodes)
            return PKIXAttributeCertificate_2009_AttributeCertificateInfo(version: version, holder: holder, issuer: issuer, signature: signature, serialNumber: serialNumber, attrCertValidityPeriod: attrCertValidityPeriod, attributes: attributes, issuerUniqueID: issuerUniqueID, extensions: extensions)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(version)
            try coder.serialize(holder)
            try coder.serialize(issuer)
            try coder.serialize(signature)
            try coder.serialize(serialNumber)
            try coder.serialize(attrCertValidityPeriod)
            try coder.serializeSequenceOf(attributes)
            if let issuerUniqueID = self.issuerUniqueID { if let issuerUniqueID = self.issuerUniqueID { try coder.serialize(issuerUniqueID) } }
            if let extensions = self.extensions { if let extensions = self.extensions { try coder.serialize(extensions) } }
        }
    }
}
