// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case compression(Raster_Gr_Coding_Attributes_Compression)
    case bits_per_colour_component(Raster_Gr_Coding_Attributes_Bits_Per_Colour_Component)
    case interleaving_format(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_interleaving_format_IntEnum)
    case number_of_pels_per_tile_line(ArraySlice<UInt8>)
    case number_of_lines_per_tile(ArraySlice<UInt8>)
    case tiling_offset(Raster_Gr_Presentation_Attributes_Coordinate_Pair)
    case tiling_types(Raster_Gr_Coding_Attributes_Tile_Type)
    case subsampling(Raster_Gr_Coding_Attributes_Subsampling)
    case jpeg_coding_mode(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_coding_mode_IntEnum)
    case jpeg_quantization_table(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_quantization_table_IntEnum)
    case jpeg_huffman_table(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_huffman_table_IntEnum)
    case jbig_tp_for_base_layer(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jbig_tp_for_base_layer_IntEnum)
    case jbig_differential_layer(Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jbig_differential_layer_IntEnum)
    case number_of_lines_per_stripe(ArraySlice<UInt8>)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific):
                self = .compression(try Raster_Gr_Coding_Attributes_Compression(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific):
                self = .bits_per_colour_component(try Raster_Gr_Coding_Attributes_Bits_Per_Colour_Component(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific):
                self = .interleaving_format(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_interleaving_format_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific):
                self = .number_of_pels_per_tile_line(try ArraySlice<UInt8>(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific):
                self = .number_of_lines_per_tile(try ArraySlice<UInt8>(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific):
                self = .tiling_offset(try Raster_Gr_Presentation_Attributes_Coordinate_Pair(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific):
                self = .tiling_types(try Raster_Gr_Coding_Attributes_Tile_Type(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 10, tagClass: .contextSpecific):
                self = .subsampling(try Raster_Gr_Coding_Attributes_Subsampling(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 11, tagClass: .contextSpecific):
                self = .jpeg_coding_mode(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_coding_mode_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 12, tagClass: .contextSpecific):
                self = .jpeg_quantization_table(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_quantization_table_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 13, tagClass: .contextSpecific):
                self = .jpeg_huffman_table(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jpeg_huffman_table_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 14, tagClass: .contextSpecific):
                self = .jbig_tp_for_base_layer(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jbig_tp_for_base_layer_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 15, tagClass: .contextSpecific):
                self = .jbig_differential_layer(try Raster_Gr_Profile_Attributes_Ra_Gr_Coding_Attribute_jbig_differential_layer_IntEnum(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 16, tagClass: .contextSpecific):
                self = .number_of_lines_per_stripe(try ArraySlice<UInt8>(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .compression(let compression): try compression.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            case .bits_per_colour_component(let bits_per_colour_component): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) { coder in try bits_per_colour_component.serialize(into: &coder) }
            case .interleaving_format(let interleaving_format): try interleaving_format.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific))
            case .number_of_pels_per_tile_line(let number_of_pels_per_tile_line): try number_of_pels_per_tile_line.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific))
            case .number_of_lines_per_tile(let number_of_lines_per_tile): try number_of_lines_per_tile.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific))
            case .tiling_offset(let tiling_offset): try tiling_offset.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific))
            case .tiling_types(let tiling_types): try tiling_types.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific))
            case .subsampling(let subsampling): try subsampling.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 10, tagClass: .contextSpecific))
            case .jpeg_coding_mode(let jpeg_coding_mode): try jpeg_coding_mode.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 11, tagClass: .contextSpecific))
            case .jpeg_quantization_table(let jpeg_quantization_table): try jpeg_quantization_table.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 12, tagClass: .contextSpecific))
            case .jpeg_huffman_table(let jpeg_huffman_table): try jpeg_huffman_table.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 13, tagClass: .contextSpecific))
            case .jbig_tp_for_base_layer(let jbig_tp_for_base_layer): try jbig_tp_for_base_layer.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 14, tagClass: .contextSpecific))
            case .jbig_differential_layer(let jbig_differential_layer): try jbig_differential_layer.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 15, tagClass: .contextSpecific))
            case .number_of_lines_per_stripe(let number_of_lines_per_stripe): try number_of_lines_per_stripe.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 16, tagClass: .contextSpecific))
        }
    }

}
