// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let SecureMimeMessageV3dot1_2009_id_cap: ASN1ObjectIdentifier = SecureMimeMessageV3dot1_2009_id_smime + [11]
