// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct SelectedAttributeTypes_TimeSpecification_time_Choice_absolute_Sequence: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var startTime: GeneralizedTime?
    @usableFromInline var endTime: GeneralizedTime?
    @inlinable init(startTime: GeneralizedTime?, endTime: GeneralizedTime?) {
        self.startTime = startTime
        self.endTime = endTime

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let startTime: GeneralizedTime? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 0, tagClass: .contextSpecific) { node in return try GeneralizedTime(derEncoded: node) }
            let endTime: GeneralizedTime? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in return try GeneralizedTime(derEncoded: node) }

            return SelectedAttributeTypes_TimeSpecification_time_Choice_absolute_Sequence(startTime: startTime, endTime: endTime)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let startTime = self.startTime { try coder.serialize(explicitlyTaggedWithTagNumber: 0, tagClass: .contextSpecific) { codec in try codec.serialize(startTime) } }
            if let endTime = self.endTime { try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serialize(endTime) } }

        }
    }
}
