// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum SelectedAttributeTypes_XDayOf: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case first(SelectedAttributeTypes_NamedDay)
    case second(SelectedAttributeTypes_NamedDay)
    case third(SelectedAttributeTypes_NamedDay)
    case fourth(SelectedAttributeTypes_NamedDay)
    case fifth(SelectedAttributeTypes_NamedDay)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific):
                self = .first(try SelectedAttributeTypes_NamedDay(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific):
                self = .second(try SelectedAttributeTypes_NamedDay(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
                self = .third(try SelectedAttributeTypes_NamedDay(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific):
                self = .fourth(try SelectedAttributeTypes_NamedDay(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific):
                self = .fifth(try SelectedAttributeTypes_NamedDay(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .first(let first): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) { coder in try first.serialize(into: &coder) }
            case .second(let second): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) { coder in try second.serialize(into: &coder) }
            case .third(let third): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) { coder in try third.serialize(into: &coder) }
            case .fourth(let fourth): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) { coder in try fourth.serialize(into: &coder) }
            case .fifth(let fifth): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific)) { coder in try fifth.serialize(into: &coder) }
        }
    }

}
