// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let SelectedAttributeTypes_id_at_encryptedCollectivePostalAddress: ASN1ObjectIdentifier = PKIX1Explicit88_id_at + [16, 1, 2]
