// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct SelectedAttributeTypes_NameAndOptionalUID: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var dn: PKIX1Explicit88_DistinguishedName
    @usableFromInline var uid: SelectedAttributeTypes_UniqueIdentifier?
    @inlinable init(dn: PKIX1Explicit88_DistinguishedName, uid: SelectedAttributeTypes_UniqueIdentifier?) {
        self.dn = dn
        self.uid = uid

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let dn: PKIX1Explicit88_DistinguishedName = try PKIX1Explicit88_DistinguishedName(derEncoded: &nodes)
            var uid: SelectedAttributeTypes_UniqueIdentifier? = nil
var peek_uid = nodes
if let next = peek_uid.next(), next.identifier == SelectedAttributeTypes_UniqueIdentifier.defaultIdentifier {
    uid = try SelectedAttributeTypes_UniqueIdentifier(derEncoded: &nodes)
}

            return SelectedAttributeTypes_NameAndOptionalUID(dn: dn, uid: uid)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(dn)
            if let uid = self.uid { try coder.serialize(uid) }

        }
    }
}
