// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let SelectedAttributeTypes_id_mr_storedPrefixMatch: ASN1ObjectIdentifier = UsefulDefinitions_id_mr + [41]
