// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let SelectedAttributeTypes_id_not_searchServiceProblem: ASN1ObjectIdentifier = UsefulDefinitions_id_not + [1]
