// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum SelectedAttributeTypes_Period_weeks_Choice: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case allWeeks(ASN1Null)
    case intWeek([ArraySlice<UInt8>])
    case bitWeek(ASN1BitString)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 0, tagClass: .application):
                self = .allWeeks(try ASN1Null(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 1, tagClass: .application):
                self = .intWeek(try DER.set(of: ArraySlice<UInt8>.self, identifier: rootNode.identifier, rootNode: rootNode))
            case ASN1Identifier(tagWithNumber: 2, tagClass: .application):
                self = .bitWeek(try ASN1BitString(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .allWeeks(let allWeeks): try allWeeks.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .application))
            case .intWeek(let intWeek): try coder.serializeSetOf(intWeek, identifier: ASN1Identifier(tagWithNumber: 1, tagClass: .application))
            case .bitWeek(let bitWeek): try bitWeek.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .application))
        }
    }

}
