// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum SelectedAttributeTypes_TimeAssertion: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case now(ASN1Null)
    case at(GeneralizedTime)
    case between(SelectedAttributeTypes_TimeAssertion_between_Sequence)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Null.defaultIdentifier:
                self = .now(try ASN1Null(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case GeneralizedTime.defaultIdentifier:
                self = .at(try GeneralizedTime(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case SelectedAttributeTypes_TimeAssertion_between_Sequence.defaultIdentifier:
                self = .between(try SelectedAttributeTypes_TimeAssertion_between_Sequence(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .now(let now): try coder.serialize(now)
            case .at(let at): try coder.serialize(at)
            case .between(let between): try coder.serialize(between)
        }
    }

}
