// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let SMIMESymmetricKeyDistribution_2009_id_skd_glRemoveOwner: ASN1ObjectIdentifier = [7]
