// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct SMIMESymmetricKeyDistribution_2009_GLUseKEK: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var glInfo: SMIMESymmetricKeyDistribution_2009_GLInfo
    @usableFromInline var glOwnerInfo: [SMIMESymmetricKeyDistribution_2009_GLOwnerInfo]
    @usableFromInline var glAdministration: SMIMESymmetricKeyDistribution_2009_GLAdministration?
    @usableFromInline var glKeyAttributes: SMIMESymmetricKeyDistribution_2009_GLKeyAttributes?
    @inlinable init(glInfo: SMIMESymmetricKeyDistribution_2009_GLInfo, glOwnerInfo: [SMIMESymmetricKeyDistribution_2009_GLOwnerInfo], glAdministration: SMIMESymmetricKeyDistribution_2009_GLAdministration?, glKeyAttributes: SMIMESymmetricKeyDistribution_2009_GLKeyAttributes?) {
        self.glInfo = glInfo
        self.glOwnerInfo = glOwnerInfo
        self.glAdministration = glAdministration
        self.glKeyAttributes = glKeyAttributes

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let glInfo: SMIMESymmetricKeyDistribution_2009_GLInfo = try SMIMESymmetricKeyDistribution_2009_GLInfo(derEncoded: &nodes)
            let glOwnerInfo: [SMIMESymmetricKeyDistribution_2009_GLOwnerInfo] = try DER.sequence(of: SMIMESymmetricKeyDistribution_2009_GLOwnerInfo.self, identifier: .sequence, nodes: &nodes)
            let glAdministration: SMIMESymmetricKeyDistribution_2009_GLAdministration? = try SMIMESymmetricKeyDistribution_2009_GLAdministration(derEncoded: &nodes)
            var glKeyAttributes: SMIMESymmetricKeyDistribution_2009_GLKeyAttributes? = nil
var peek_glKeyAttributes = nodes
if let next = peek_glKeyAttributes.next(), next.identifier == SMIMESymmetricKeyDistribution_2009_GLKeyAttributes.defaultIdentifier {
    glKeyAttributes = try SMIMESymmetricKeyDistribution_2009_GLKeyAttributes(derEncoded: &nodes)
}

            return SMIMESymmetricKeyDistribution_2009_GLUseKEK(glInfo: glInfo, glOwnerInfo: glOwnerInfo, glAdministration: glAdministration, glKeyAttributes: glKeyAttributes)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(glInfo)
            try coder.serializeSequenceOf(glOwnerInfo)
            if let glAdministration = self.glAdministration { try coder.serialize(glAdministration) }
            if let glKeyAttributes = self.glKeyAttributes { try coder.serialize(glKeyAttributes) }

        }
    }
}
