// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum Style_Descriptors_Same_Layout_Object_layout_object_Choice: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case d(Identifiers_and_Expressions_Object_or_Class_Identifier)
    case to_stream_root_category(Identifiers_and_Expressions_Category_Name)
    case to_stream_sub_category(Identifiers_and_Expressions_Category_Name)
    case to_layout_category(Identifiers_and_Expressions_Category_Name)
    case e(Layout_Descriptors_Layout_Object_Type)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific):
                self = .d(try Identifiers_and_Expressions_Object_or_Class_Identifier(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific):
                self = .to_stream_root_category(try Identifiers_and_Expressions_Category_Name(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific):
                self = .to_stream_sub_category(try Identifiers_and_Expressions_Category_Name(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific):
                self = .to_layout_category(try Identifiers_and_Expressions_Category_Name(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
                self = .e(try Layout_Descriptors_Layout_Object_Type(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .d(let d): try d.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            case .to_stream_root_category(let to_stream_root_category): try to_stream_root_category.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific))
            case .to_stream_sub_category(let to_stream_sub_category): try to_stream_sub_category.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific))
            case .to_layout_category(let to_layout_category): try to_layout_category.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            case .e(let e): try e.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
        }
    }

}
