// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Style_Descriptors_Offset: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var leading: ArraySlice<UInt8>?
    @usableFromInline var trailing: ArraySlice<UInt8>?
    @usableFromInline var left_hand: ArraySlice<UInt8>?
    @usableFromInline var right_hand: ArraySlice<UInt8>?
    @inlinable init(leading: ArraySlice<UInt8>?, trailing: ArraySlice<UInt8>?, left_hand: ArraySlice<UInt8>?, right_hand: ArraySlice<UInt8>?) {
        self.leading = leading
        self.trailing = trailing
        self.left_hand = left_hand
        self.right_hand = right_hand
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let leading: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            let trailing: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let left_hand: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let right_hand: ArraySlice<UInt8>? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            return Style_Descriptors_Offset(leading: leading, trailing: trailing, left_hand: left_hand, right_hand: right_hand)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let leading = self.leading { if let leading = self.leading { try coder.serializeOptionalImplicitlyTagged(leading, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) } }
            if let trailing = self.trailing { if let trailing = self.trailing { try coder.serializeOptionalImplicitlyTagged(trailing, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) } }
            if let left_hand = self.left_hand { if let left_hand = self.left_hand { try coder.serializeOptionalImplicitlyTagged(left_hand, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) } }
            if let right_hand = self.right_hand { if let right_hand = self.right_hand { try coder.serializeOptionalImplicitlyTagged(right_hand, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) } }
        }
    }
}
