// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Subprofiles_Document_Fragment_Description: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var title: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var subject: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var document_fragment_type: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var abstract: Document_Profile_Descriptor_Character_Data?
    @usableFromInline var keywords: [Document_Profile_Descriptor_Character_Data]?
    @inlinable init(title: Document_Profile_Descriptor_Character_Data?, subject: Document_Profile_Descriptor_Character_Data?, document_fragment_type: Document_Profile_Descriptor_Character_Data?, abstract: Document_Profile_Descriptor_Character_Data?, keywords: [Document_Profile_Descriptor_Character_Data]?) {
        self.title = title
        self.subject = subject
        self.document_fragment_type = document_fragment_type
        self.abstract = abstract
        self.keywords = keywords

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let title: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let subject: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            let document_fragment_type: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            let abstract: Document_Profile_Descriptor_Character_Data? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            let keywords: [Document_Profile_Descriptor_Character_Data]? = try DER.optionalImplicitlyTagged(&nodes, tagNumber: 4, tagClass: .contextSpecific) { node in try DER.set(of: Document_Profile_Descriptor_Character_Data.self, identifier: node.identifier, rootNode: node) }

            return Subprofiles_Document_Fragment_Description(title: title, subject: subject, document_fragment_type: document_fragment_type, abstract: abstract, keywords: keywords)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let title = self.title { try coder.serializeOptionalImplicitlyTagged(title, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            if let subject = self.subject { try coder.serializeOptionalImplicitlyTagged(subject, withIdentifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) }
            if let document_fragment_type = self.document_fragment_type { try coder.serializeOptionalImplicitlyTagged(document_fragment_type, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) }
            if let abstract = self.abstract { try coder.serializeOptionalImplicitlyTagged(abstract, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific)) }
            if let keywords = self.keywords { try coder.serializeSetOf(keywords, identifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific)) }

        }
    }
}
