// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Temporal_Relationships_Temporal_Relations: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var synchronization_type: Temporal_Relationships_Synchronization_Type
    @usableFromInline var subordinate_nodes: [Temporal_Relationships_Temporal_Relations_subordinate_nodes_Set]
    @inlinable init(synchronization_type: Temporal_Relationships_Synchronization_Type, subordinate_nodes: [Temporal_Relationships_Temporal_Relations_subordinate_nodes_Set]) {
        self.synchronization_type = synchronization_type
        self.subordinate_nodes = subordinate_nodes
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let synchronization_type: Temporal_Relationships_Synchronization_Type = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)))!
            let subordinate_nodes: [Temporal_Relationships_Temporal_Relations_subordinate_nodes_Set] = try DER.explicitlyTagged(&nodes, tagNumber: 1, tagClass: .contextSpecific) { node in try DER.sequence(of: Temporal_Relationships_Temporal_Relations_subordinate_nodes_Set.self, identifier: .sequence, rootNode: node) }
            return Temporal_Relationships_Temporal_Relations(synchronization_type: synchronization_type, subordinate_nodes: subordinate_nodes)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serializeOptionalImplicitlyTagged(synchronization_type, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            try coder.serialize(explicitlyTaggedWithTagNumber: 1, tagClass: .contextSpecific) { codec in try codec.serializeSequenceOf(subordinate_nodes) }
        }
    }
}
