// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct Temporal_Relationships_Presentation_Time: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .set }
    @usableFromInline var timing: Temporal_Relationships_Presentation_Time_timing_Choice?
    @usableFromInline var duration: Temporal_Relationships_Presentation_Time_duration_Choice?
    @usableFromInline var cyclic: Temporal_Relationships_Cyclic?
    @inlinable init(timing: Temporal_Relationships_Presentation_Time_timing_Choice?, duration: Temporal_Relationships_Presentation_Time_duration_Choice?, cyclic: Temporal_Relationships_Cyclic?) {
        self.timing = timing
        self.duration = duration
        self.cyclic = cyclic
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.set(root, identifier: identifier) { nodes in
            let timing: Temporal_Relationships_Presentation_Time_timing_Choice? = try Temporal_Relationships_Presentation_Time_timing_Choice(derEncoded: &nodes)
            let duration: Temporal_Relationships_Presentation_Time_duration_Choice? = try Temporal_Relationships_Presentation_Time_duration_Choice(derEncoded: &nodes)
            let cyclic: Temporal_Relationships_Cyclic? = try DER.optionalExplicitlyTagged(&nodes, tagNumber: 5, tagClass: .contextSpecific) { node in return try Temporal_Relationships_Cyclic(derEncoded: node) }
            return Temporal_Relationships_Presentation_Time(timing: timing, duration: duration, cyclic: cyclic)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let timing = self.timing { if let timing = self.timing { try coder.serialize(timing) } }
            if let duration = self.duration { if let duration = self.duration { try coder.serialize(duration) } }
            if let cyclic = self.cyclic { if let cyclic = self.cyclic { try coder.serialize(explicitlyTaggedWithTagNumber: 5, tagClass: .contextSpecific) { codec in try codec.serialize(cyclic) } } }
        }
    }
}
