// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

public let UsefulDefinitions_opBindingManagement: ASN1ObjectIdentifier = UsefulDefinitions_module + [18, 3]
