// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct KEP_OcspResponsesID: DERImplicitlyTaggable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var ocspIdentifier: KEP_OcspIdentifier
    @usableFromInline var ocspRepHash: KEP_OtherHash?
    @inlinable init(ocspIdentifier: KEP_OcspIdentifier, ocspRepHash: KEP_OtherHash?) {
        self.ocspIdentifier = ocspIdentifier
        self.ocspRepHash = ocspRepHash
    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let ocspIdentifier: KEP_OcspIdentifier = try KEP_OcspIdentifier(derEncoded: &nodes)
            var ocspRepHash: KEP_OtherHash? = nil
var peek_ocspRepHash = nodes
if let next = peek_ocspRepHash.next(), next.identifier == KEP_OtherHash.defaultIdentifier {
    ocspRepHash = try KEP_OtherHash(derEncoded: &nodes)
}
            return KEP_OcspResponsesID(ocspIdentifier: ocspIdentifier, ocspRepHash: ocspRepHash)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(ocspIdentifier)
            if let ocspRepHash = self.ocspRepHash { if let ocspRepHash = self.ocspRepHash { try coder.serialize(ocspRepHash) } }
        }
    }
}
