// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline indirect enum LDAP_Filter: DERImplicitlyTaggable, DERParseable, DERSerializable, Hashable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case and([LDAP_Filter])
    case or([LDAP_Filter])
    case not(LDAP_Filter)
    case equalityMatch(LDAP_AttributeValueAssertion)
    case substrings(LDAP_SubstringFilter)
    case greaterOrEqual(LDAP_AttributeValueAssertion)
    case lessOrEqual(LDAP_AttributeValueAssertion)
    case present(ASN1OctetString)
    case approxMatch(LDAP_AttributeValueAssertion)
    case extensibleMatch(LDAP_MatchingRuleAssertion)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
            case ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific):
                self = .and(try DER.set(of: LDAP_Filter.self, identifier: rootNode.identifier, rootNode: rootNode))
            case ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific):
                self = .or(try DER.set(of: LDAP_Filter.self, identifier: rootNode.identifier, rootNode: rootNode))
            case ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific):
                self = .not(try LDAP_Filter(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific):
                self = .equalityMatch(try LDAP_AttributeValueAssertion(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific):
                self = .substrings(try LDAP_SubstringFilter(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific):
                self = .greaterOrEqual(try LDAP_AttributeValueAssertion(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific):
                self = .lessOrEqual(try LDAP_AttributeValueAssertion(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific):
                self = .present(try ASN1OctetString(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific):
                self = .approxMatch(try LDAP_AttributeValueAssertion(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            case ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific):
                self = .extensibleMatch(try LDAP_MatchingRuleAssertion(derEncoded: rootNode, withIdentifier: rootNode.identifier))

            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
            case .and(let and): try coder.serializeSetOf(and, identifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            case .or(let or): try coder.serializeSetOf(or, identifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific))
            case .not(let not): try not.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific))
            case .equalityMatch(let equalityMatch): try equalityMatch.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 3, tagClass: .contextSpecific))
            case .substrings(let substrings): try substrings.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 4, tagClass: .contextSpecific))
            case .greaterOrEqual(let greaterOrEqual): try greaterOrEqual.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 5, tagClass: .contextSpecific))
            case .lessOrEqual(let lessOrEqual): try lessOrEqual.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 6, tagClass: .contextSpecific))
            case .present(let present): try present.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 7, tagClass: .contextSpecific))
            case .approxMatch(let approxMatch): try approxMatch.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 8, tagClass: .contextSpecific))
            case .extensibleMatch(let extensibleMatch): try extensibleMatch.serialize(into: &coder, withIdentifier: ASN1Identifier(tagWithNumber: 9, tagClass: .contextSpecific))

        }
    }

}
