List DEFINITIONS IMPLICIT TAGS ::= BEGIN



  K ::= SEQUENCE {

    w SET OF
      SEQUENCE OF
      SET OF
      SEQUENCE OF
      SET OF
      SEQUENCE OF
      SET OF
      SEQUENCE OF
      SET OF
      SEQUENCE OF
      SET OF
      SEQUENCE OF INTEGER
  }

END
